# EMCAPI

networking:
  # IP the API will listen on
  host: 127.0.0.1

  # Port the API will listen on
  port: 8080

  # The version number for endpoints
  api_version: 3

  # The URL path, formatted as: https://example.com/{api_version}/{url_path}
  url_path: aurora

behaviour:
  # The maximum entries a player can enter when looking up objects by name
  max_lookup_size: 100

  # Setting for testing reasons
  developer_mode: false

  # Should legacy endpoints (if any) be loaded?
  load_legacy: true

database:
  host: 127.0.0.1
  port: 3306
  username: 'root'
  password: ''
  name: emcapi
  min-pool-size: 0
  max-pool-size: 1
  flags: ''
