name: EMCAPI
version: "${project.version}"
main: net.earthmc.emcapi.EMCAPI
api-version: "1.20"
depend: [Towny, Quarters, DiscordSRV, SuperbVote]
softdepend: [MysteryMaster]
authors: [Fruitloopins]
contributors: [Warriorrr, Yoditi]
description: API for EarthMC using Javalin
website: https://earthmc.net
folia-supported: true
commands:
  api:
    description: Allow players to opt out