name: EMCAPI
version: "${project.version}"
main: net.earthmc.emcapi.EMCAPI
api-version: "1.19"
depend: [Towny, Quarters, Vault, DiscordSRV]
authors: [Fruitloopins]
description: API for EarthMC using Javalin
website: https://earthmc.net
